package black.parsebot.event;

public enum EventType {
	CONSECUTIVE_FAILURES,
	REPORT_CARD,
	NOTIFICATION_FAILED,
	MESSAGE_PROCESSING_FAILED,
	PIPELINE_RUN_FAILED,
	CLAUDE_API_FAILED,
	SFTP_WRITE_FAILED,
	MAILBOX_READ_FAILED,
	MAILBOX_WRITE_FAILED
}
